# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentbox',
            name='content',
        ),
    ]
